/* fetch data at build time, maybe stale */

import Head from "next/head";
import Image from "next/image";
import { gql } from "@apollo/client";
import client from "../apollo-client";

export default function Home({ countries }) {
  return (
    <div className="px-8">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen py-16 flex flex-col justify-center items-center">
        <h1 className="text-2xl text-center">
          Welcome to{" "}
          <a
            className="text-blue-600 hover:underline focus:underline"
            href="https://nextjs.org"
          >
            Next.js!
          </a>
        </h1>

        <p className="my-16 text-2xl text-center">
          Get started by editing{" "}
          <code className="bg-gray-50 rounded-md p-3 text-lg font-mono">
            pages/index.js
          </code>
        </p>

        <div className="flex items-center justify-center flex-wrap max-w-3xl">
          {countries.map((country) => (
            <div
              key={country.code}
              className="m-4 p-6 border border-solid border-gray-400 rounded-lg w-full md:max-w-xs hover:text-blue-600 hover:border-blue-600 transition-all"
            >
              <h3>
                <a
                  href="#country-name"
                  aria-hidden="true"
                  className="aal_anchor"
                  id="country-name"
                >
                  <svg
                    aria-hidden="true"
                    className="aal_svg"
                    height="16"
                    version="1.1"
                    viewBox="0 0 16 16"
                    width="16"
                  >
                    <path
                      fillRule="evenodd"
                      d="M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z"
                    ></path>
                  </svg>
                </a>
                {country.name}
              </h3>
              <p className="text-lg">
                {country.code} - {country.emoji}
              </p>
            </div>
          ))}
        </div>
      </main>

      <footer className="flex flex-1 py-8 border-t border-solid border-gray-400 justify-center items-center">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          className="flex justify-center items-center grow"
        >
          Powered by{" "}
          <span className="h-4 ml-2">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>{" "}
          , tailwindCSS, apollo/client, zustand
        </a>
      </footer>
    </div>
  );
}

export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
      query Countries {
        countries {
          code
          name
          emoji
        }
      }
    `,
  });

  return {
    props: {
      countries: data.countries.slice(0, 4),
    },
  };
}
